
package rassus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SensorServerService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:9000/SensorServer?wsdl")
public class SensorServerService
    extends Service
{

    private final static URL SENSORSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENSORSERVERSERVICE_EXCEPTION;
    private final static QName SENSORSERVERSERVICE_QNAME = new QName("http://example/", "SensorServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/SensorServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENSORSERVERSERVICE_WSDL_LOCATION = url;
        SENSORSERVERSERVICE_EXCEPTION = e;
    }

    public SensorServerService() {
        super(__getWsdlLocation(), SENSORSERVERSERVICE_QNAME);
    }

    public SensorServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENSORSERVERSERVICE_QNAME, features);
    }

    public SensorServerService(URL wsdlLocation) {
        super(wsdlLocation, SENSORSERVERSERVICE_QNAME);
    }

    public SensorServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENSORSERVERSERVICE_QNAME, features);
    }

    public SensorServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SensorServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SensorServer
     */
    @WebEndpoint(name = "SensorServerPort")
    public SensorServer getSensorServerPort() {
        return super.getPort(new QName("http://example/", "SensorServerPort"), SensorServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SensorServer
     */
    @WebEndpoint(name = "SensorServerPort")
    public SensorServer getSensorServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "SensorServerPort"), SensorServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENSORSERVERSERVICE_EXCEPTION!= null) {
            throw SENSORSERVERSERVICE_EXCEPTION;
        }
        return SENSORSERVERSERVICE_WSDL_LOCATION;
    }

}
